use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FlowFeatureType {
    FlowId,
    SrcIp,
    SrcPort,
    DstIp,
    DstPort,
    Protocol,
    Timestamp,
    FlowDuration,
    TotFwdPkt,
    TotBwdPkt,
    TotLenFwdPkt,
    TotLenBwdPkt,
    FwdPktLenMax,
    FwdPktLenMin,
    FwdPktLenMean,
    FwdPktLenStd,
    BwdPktLenMax,
    BwdPktLenMin,
    BwdPktLenMean,
    BwdPktLenStd,
    FlowBytesSec,
    FlowPktsSec,
    FlowIatMean,
    FlowIatStd,
    FlowIatMax,
    FlowIatMin,
    FwdIatTot,
    FwdIatMean,
    FwdIatStd,
    FwdIatMax,
    FwdIatMin,
    BwdIatTot,
    BwdIatMean,
    BwdIatStd,
    BwdIatMax,
    BwdIatMin,
    FwdPshFlags,
    BwdPshFlags,
    FwdUrgFlags,
    BwdUrgFlags,
    FwdHdrLen,
    BwdHdrLen,
    FwdPktsSec,
    BwdPktsSec,
    PktLenMin,
    PktLenMax,
    PktLenMean,
    PktLenStd,
    PktLenVar,
    FinCnt,
    SynCnt,
    RstCnt,
    PshCnt,
    AckCnt,
    UrgCnt,
    CwrCnt,
    EceCnt,
    DownUpRatio,
    PktSizeAvg,
    FwdSegAvg,
    BwdSegAvg,
    FwdBytesBulkAvg,
    FwdPktBulkAvg,
    FwdBulkRateAvg,
    BwdBytesBulkAvg,
    BwdPktBulkAvg,
    BwdBulkRateAvg,
    SubflFwdPkt,
    SubflFwdByt,
    SubflBwdPkt,
    SubflBwdByt,
    FwdWinByt,
    BwdWinByt,
    FwdActPkt,
    FwdSegMin,
    ActiveMean,
    ActiveStd,
    ActiveMax,
    ActiveMin,
    IdleMean,
    IdleStd,
    IdleMax,
    IdleMin,
    Label,
}

pub const CIC_FEATURE_NAMES: [&str; 84] = [
    "Flow ID",
    "Src IP",
    "Src Port",
    "Dst IP",
    "Dst Port",
    "Protocol",
    "Timestamp",
    "Flow Duration",
    "Total Fwd Packet",
    "Total Bwd packets",
    "Total Length of Fwd Packet",
    "Total Length of Bwd Packet",
    "Fwd Packet Length Max",
    "Fwd Packet Length Min",
    "Fwd Packet Length Mean",
    "Fwd Packet Length Std",
    "Bwd Packet Length Max",
    "Bwd Packet Length Min",
    "Bwd Packet Length Mean",
    "Bwd Packet Length Std",
    "Flow Bytes/s",
    "Flow Packets/s",
    "Flow IAT Mean",
    "Flow IAT Std",
    "Flow IAT Max",
    "Flow IAT Min",
    "Fwd IAT Total",
    "Fwd IAT Mean",
    "Fwd IAT Std",
    "Fwd IAT Max",
    "Fwd IAT Min",
    "Bwd IAT Total",
    "Bwd IAT Mean",
    "Bwd IAT Std",
    "Bwd IAT Max",
    "Bwd IAT Min",
    "Fwd PSH Flags",
    "Bwd PSH Flags",
    "Fwd URG Flags",
    "Bwd URG Flags",
    "Fwd Header Length",
    "Bwd Header Length",
    "Fwd Packets/s",
    "Bwd Packets/s",
    "Packet Length Min",
    "Packet Length Max",
    "Packet Length Mean",
    "Packet Length Std",
    "Packet Length Variance",
    "FIN Flag Count",
    "SYN Flag Count",
    "RST Flag Count",
    "PSH Flag Count",
    "ACK Flag Count",
    "URG Flag Count",
    "CWR Flag Count",
    "ECE Flag Count",
    "Down/Up Ratio",
    "Average Packet Size",
    "Fwd Segment Size Avg",
    "Bwd Segment Size Avg",
    "Fwd Bytes/Bulk Avg",
    "Fwd Packet/Bulk Avg",
    "Fwd Bulk Rate Avg",
    "Bwd Bytes/Bulk Avg",
    "Bwd Packet/Bulk Avg",
    "Bwd Bulk Rate Avg",
    "Subflow Fwd Packets",
    "Subflow Fwd Bytes",
    "Subflow Bwd Packets",
    "Subflow Bwd Bytes",
    "FWD Init Win Bytes",
    "Bwd Init Win Bytes",
    "Fwd Act Data Pkts",
    "Fwd Seg Size Min",
    "Active Mean",
    "Active Std",
    "Active Max",
    "Active Min",
    "Idle Mean",
    "Idle Std",
    "Idle Max",
    "Idle Min",
    "Label",
];

pub fn get_csv_header() -> String {
    CIC_FEATURE_NAMES.join(",")
}

#[inline]
pub fn format_java_double(val: f64) -> String {
    if val.is_nan() {
        "0.0".to_string()
    } else if val.is_infinite() {
        if val > 0.0 {
            "Infinity".to_string()
        } else {
            "-Infinity".to_string()
        }
    } else {
        let s = val.to_string();
        if !s.contains('.') && !s.contains('e') && !s.contains('E') {
            format!("{}.0", s)
        } else {
            s
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FlowFeatures {
    pub flow_id: String,
    pub src_ip: String,
    pub src_port: u16,
    pub dst_ip: String,
    pub dst_port: u16,
    pub protocol: u8,
    pub timestamp: String,
    pub flow_duration: i64,
    pub tot_fwd_pkts: u64,
    pub tot_bwd_pkts: u64,
    pub tot_len_fwd_pkts: f64,
    pub tot_len_bwd_pkts: f64,
    pub fwd_pkt_len_max: f64,
    pub fwd_pkt_len_min: f64,
    pub fwd_pkt_len_mean: f64,
    pub fwd_pkt_len_std: f64,
    pub bwd_pkt_len_max: f64,
    pub bwd_pkt_len_min: f64,
    pub bwd_pkt_len_mean: f64,
    pub bwd_pkt_len_std: f64,
    pub flow_bytes_sec: f64,
    pub flow_pkts_sec: f64,
    pub flow_iat_mean: f64,
    pub flow_iat_std: f64,
    pub flow_iat_max: f64,
    pub flow_iat_min: f64,
    pub fwd_iat_tot: f64,
    pub fwd_iat_mean: f64,
    pub fwd_iat_std: f64,
    pub fwd_iat_max: f64,
    pub fwd_iat_min: f64,
    pub bwd_iat_tot: f64,
    pub bwd_iat_mean: f64,
    pub bwd_iat_std: f64,
    pub bwd_iat_max: f64,
    pub bwd_iat_min: f64,
    pub fwd_psh_flags: u32,
    pub bwd_psh_flags: u32,
    pub fwd_urg_flags: u32,
    pub bwd_urg_flags: u32,
    pub fwd_hdr_len: u64,
    pub bwd_hdr_len: u64,
    pub fwd_pkts_sec: f64,
    pub bwd_pkts_sec: f64,
    pub pkt_len_min: f64,
    pub pkt_len_max: f64,
    pub pkt_len_mean: f64,
    pub pkt_len_std: f64,
    pub pkt_len_var: f64,
    pub fin_cnt: u32,
    pub syn_cnt: u32,
    pub rst_cnt: u32,
    pub psh_cnt: u32,
    pub ack_cnt: u32,
    pub urg_cnt: u32,
    pub cwr_cnt: u32,
    pub ece_cnt: u32,
    pub down_up_ratio: f64,
    pub pkt_size_avg: f64,
    pub fwd_seg_avg: f64,
    pub bwd_seg_avg: f64,
    pub fwd_bytes_bulk_avg: u64,
    pub fwd_pkt_bulk_avg: u64,
    pub fwd_bulk_rate_avg: u64,
    pub bwd_bytes_bulk_avg: u64,
    pub bwd_pkt_bulk_avg: u64,
    pub bwd_bulk_rate_avg: u64,
    pub subfl_fwd_pkt: u64,
    pub subfl_fwd_byt: u64,
    pub subfl_bwd_pkt: u64,
    pub subfl_bwd_byt: u64,
    pub fwd_win_byt: u32,
    pub bwd_win_byt: u32,
    pub fwd_act_pkt: u64,
    pub fwd_seg_min: u64,
    pub active_mean: f64,
    pub active_std: f64,
    pub active_max: f64,
    pub active_min: f64,
    pub idle_mean: f64,
    pub idle_std: f64,
    pub idle_max: f64,
    pub idle_min: f64,
    pub label: String,
}

impl FlowFeatures {
    pub fn to_csv_row(&self) -> String {
        format!(
            "{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}",
            self.flow_id,
            self.src_ip,
            self.src_port,
            self.dst_ip,
            self.dst_port,
            self.protocol,
            self.timestamp,
            self.flow_duration,
            self.tot_fwd_pkts,
            self.tot_bwd_pkts,
            format_java_double(self.tot_len_fwd_pkts),
            format_java_double(self.tot_len_bwd_pkts),
            format_java_double(self.fwd_pkt_len_max),
            format_java_double(self.fwd_pkt_len_min),
            format_java_double(self.fwd_pkt_len_mean),
            format_java_double(self.fwd_pkt_len_std),
            format_java_double(self.bwd_pkt_len_max),
            format_java_double(self.bwd_pkt_len_min),
            format_java_double(self.bwd_pkt_len_mean),
            format_java_double(self.bwd_pkt_len_std),
            format_java_double(self.flow_bytes_sec),
            format_java_double(self.flow_pkts_sec),
            format_java_double(self.flow_iat_mean),
            format_java_double(self.flow_iat_std),
            format_java_double(self.flow_iat_max),
            format_java_double(self.flow_iat_min),
            format_java_double(self.fwd_iat_tot),
            format_java_double(self.fwd_iat_mean),
            format_java_double(self.fwd_iat_std),
            format_java_double(self.fwd_iat_max),
            format_java_double(self.fwd_iat_min),
            format_java_double(self.bwd_iat_tot),
            format_java_double(self.bwd_iat_mean),
            format_java_double(self.bwd_iat_std),
            format_java_double(self.bwd_iat_max),
            format_java_double(self.bwd_iat_min),
            self.fwd_psh_flags,
            self.bwd_psh_flags,
            self.fwd_urg_flags,
            self.bwd_urg_flags,
            self.fwd_hdr_len,
            self.bwd_hdr_len,
            format_java_double(self.fwd_pkts_sec),
            format_java_double(self.bwd_pkts_sec),
            format_java_double(self.pkt_len_min),
            format_java_double(self.pkt_len_max),
            format_java_double(self.pkt_len_mean),
            format_java_double(self.pkt_len_std),
            format_java_double(self.pkt_len_var),
            self.fin_cnt,
            self.syn_cnt,
            self.rst_cnt,
            self.psh_cnt,
            self.ack_cnt,
            self.urg_cnt,
            self.cwr_cnt,
            self.ece_cnt,
            format_java_double(self.down_up_ratio),
            format_java_double(self.pkt_size_avg),
            format_java_double(self.fwd_seg_avg),
            format_java_double(self.bwd_seg_avg),
            self.fwd_bytes_bulk_avg,
            self.fwd_pkt_bulk_avg,
            self.fwd_bulk_rate_avg,
            self.bwd_bytes_bulk_avg,
            self.bwd_pkt_bulk_avg,
            self.bwd_bulk_rate_avg,
            self.subfl_fwd_pkt,
            self.subfl_fwd_byt,
            self.subfl_bwd_pkt,
            self.subfl_bwd_byt,
            self.fwd_win_byt,
            self.bwd_win_byt,
            self.fwd_act_pkt,
            self.fwd_seg_min,
            format_java_double(self.active_mean),
            format_java_double(self.active_std),
            format_java_double(self.active_max),
            format_java_double(self.active_min),
            format_java_double(self.idle_mean),
            format_java_double(self.idle_std),
            format_java_double(self.idle_max),
            format_java_double(self.idle_min),
            self.label
        )
    }
}
