#!/usr/bin/env python3
"""
Automated Feature Parity and Correlation Assessor
Compares CSV files generated by Java CICFlowMeter vs Rust CICFlowMeter.
"""

import sys
import os
import pandas as pd
import numpy as np

def compare_csvs(java_csv_path, rust_csv_path):
    print("=" * 70)
    print("  CICFlowMeter Correctness & Feature Parity Assessment")
    print("=" * 70)
    print(f"Java Reference CSV : {java_csv_path}")
    print(f"Rust Generated CSV : {rust_csv_path}")

    if not os.path.exists(java_csv_path):
        print(f"Error: Java CSV not found at {java_csv_path}")
        sys.exit(1)
    if not os.path.exists(rust_csv_path):
        print(f"Error: Rust CSV not found at {rust_csv_path}")
        sys.exit(1)

    df_java = pd.read_csv(java_csv_path)
    df_rust = pd.read_csv(rust_csv_path)

    df_java.columns = [c.strip() for c in df_java.columns]
    df_rust.columns = [c.strip() for c in df_rust.columns]

    print(f"\nFlow Counts:")
    print(f"  Java flows extracted : {len(df_java)}")
    print(f"  Rust flows extracted : {len(df_rust)}")

    def make_key(row):
        ips = sorted([str(row['Src IP']), str(row['Dst IP'])])
        ports = sorted([int(row['Src Port']), int(row['Dst Port'])])
        return f"{ips[0]}:{ports[0]}-{ips[1]}:{ports[1]}-{row['Protocol']}"

    df_java['match_key'] = df_java.apply(make_key, axis=1)
    df_rust['match_key'] = df_rust.apply(make_key, axis=1)

    merged = pd.merge(df_java, df_rust, on='match_key', suffixes=('_java', '_rust'))
    print(f"  Bidirectionally matched flows : {len(merged)}")

    numeric_cols = [
        "Flow Duration", "Total Fwd Packet", "Total Bwd packets",
        "Total Length of Fwd Packet", "Total Length of Bwd Packet",
        "Fwd Packet Length Max", "Fwd Packet Length Min", "Fwd Packet Length Mean", "Fwd Packet Length Std",
        "Bwd Packet Length Max", "Bwd Packet Length Min", "Bwd Packet Length Mean", "Bwd Packet Length Std",
        "Flow Bytes/s", "Flow Packets/s", "Flow IAT Mean", "Flow IAT Std", "Flow IAT Max", "Flow IAT Min",
        "Fwd IAT Total", "Fwd IAT Mean", "Fwd IAT Max", "Fwd IAT Min",
        "Bwd IAT Total", "Bwd IAT Mean", "Bwd IAT Max", "Bwd IAT Min",
        "FIN Flag Count", "SYN Flag Count", "RST Flag Count", "PSH Flag Count", "ACK Flag Count",
        "FWD Init Win Bytes", "Bwd Init Win Bytes", "Fwd Act Data Pkts", "Fwd Seg Size Min",
        "Active Mean", "Idle Mean"
    ]

    print("\n" + "=" * 80)
    print(f"{'Feature Name':<30} | {'MAE':<10} | {'Max Diff':<10} | {'Pearson r':<10} | {'Status'}")
    print("-" * 80)

    total_checked = 0
    exact_matches = 0

    for col in numeric_cols:
        if f"{col}_java" in merged.columns and f"{col}_rust" in merged.columns:
            total_checked += 1
            v_j = merged[f"{col}_java"].astype(float)
            v_r = merged[f"{col}_rust"].astype(float)
            diff = np.abs(v_j - v_r)
            mae = diff.mean()
            max_err = diff.max()
            std_j = np.std(v_j)
            std_r = np.std(v_r)
            corr = np.corrcoef(v_j, v_r)[0, 1] if len(v_j) > 1 and std_j > 0 and std_r > 0 else 1.0
            if np.isnan(corr):
                corr = 1.0

            if max_err < 1e-3:
                status = "EXACT (100%)"
                exact_matches += 1
            elif corr > 0.999:
                status = "CONCORDANT"
                exact_matches += 1
            else:
                status = "DISCREPANCY"

            print(f"{col:<30} | {mae:<10.4f} | {max_err:<10.4f} | {corr:<10.4f} | {status}")

    print("=" * 80)
    concordance_rate = (exact_matches / total_checked) * 100 if total_checked > 0 else 0
    print(f"Overall Feature Concordance Rate: {concordance_rate:.2f}% ({exact_matches}/{total_checked} feature categories)")
    print("=" * 80 + "\n")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: compare_outputs.py <java_csv> <rust_csv>")
        sys.exit(1)
    compare_csvs(sys.argv[1], sys.argv[2])
